import { ComputeModule } from '@palantir/compute-module';
import type { Client } from "@osdk/client";

export const TYPES = {
    FoundryClient: Symbol.for("FoundryClient"),
    WeatherService: Symbol.for("WeatherService"),
    WorldDao: Symbol.for("WorldDao"),
    UserDao: Symbol.for("UserDao"),
};

export interface Token {
    readonly access_token: string;
    readonly expires_in: number;
    readonly refresh_token?: string;
    readonly expires_at: number;
}

export interface BaseOauthClient {
    (): Promise<string>;
    getTokenOrUndefined: () => string | undefined;
    signIn: () => Promise<Token>;
    signOut: () => Promise<void>;
}

export interface FoundryClient {
    client: Client;
    auth: BaseOauthClient;
    ontologyRid: string;
    url: string;
    getUser: () => Promise<User>;
}

// Basic example of calling other services besides Foundry.
export interface WeatherService {
    (city: string): Promise<string>;
}

export interface APIError extends Error {
    response?: {
        data: any;
    };
}

export interface ModuleConfig {
    isTest?: boolean;
}

export interface TestModule {
    listeners: Record<string, any>;
    on(event: string, handler: Function): TestModule;
    register(operation: string, handler: Function): TestModule;
}

export type ComputeModuleType = TestModule | ComputeModule<any>;

export interface GreetingInput {
    message: string;
    userId: string;
}

export interface GreetingResult {
    id: string;
    greeting: string;
}

export interface User {
    id: string;
    username: string;
    givenName?: string;
    familyName?: string;
    email?: string;
    organization?: string;
    attributes: Record<string, any>;
}

export interface MachineExecutions {
    /** Current State */
    /** holds the current state of the state machine */
    currentState: string | undefined;
    /** Id */
    /** The uuid of the machine execution. It uniquely identifies the machine. */
    readonly id: string;
    /** Logs */
    /** Holds the execution logs from a machine execution. The logs are generated by the TypeScript functions */
    logs: string | undefined;
    /** Machine */
    /** Holds the state machine generated for the solution. The machine is a JSON string using the x-reason JSON schema. */
    machine: string | undefined;
    /** State */
    /** The current state of the state machine execution */
    state: string | undefined;
    /** Delete the object. The object will no longer appear in any links and its properties will no longer be accessible. */
    delete(): void;
}

export type WorldDao = (input: GreetingInput) => Promise<GreetingResult>;
export type UserDao = () => Promise<User>;
export type MachineDao = (machineExecutionId: string) => Promise<MachineExecutions>;