name: jest-tests

on:
  pull_request:
    branches:
      - master
  deployment_status:

jobs:
  run-e2es:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          echo "Installing all dependencies from the root..."
          npm ci

      - name: Build Affected Projects
        run: |
          echo "Building affected projects..."
          npx nx affected --target=build --base=origin/${{ github.base_ref }} --parallel=3

      - name: Run Tests on Affected Projects
        run: |
          echo "Running tests for affected projects..."
          npx nx affected --target=test --base=origin/${{ github.base_ref }} --parallel=3
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url || 'http://localhost:3000' }}
          GITLAB_HOST: https://gitlabhubdev.chemli.app
          GITLAB_ROOT_TOKEN: ${{secrets.GITLAB_ROOT_TOKEN}}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          BLOB_READ_WRITE_TOKEN: ${{secrets.BLOB_READ_WRITE_TOKEN}}
          KV_REST_API_READ_ONLY_TOKEN: ${{secrets.KV_REST_API_READ_ONLY_TOKEN}}
          KV_REST_API_TOKEN: ${{secrets.KV_REST_API_TOKEN}}
          KV_REST_API_URL: ${{secrets.KV_REST_API_URL}}
          KV_URL: ${{secrets.KV_URL}}
